# -*- coding: utf-8 -*-
"""simple_code0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sIefaKyqbqxHca9vRuNRm_apHgOzlPOh
"""

import pandas as pd

# Create data as a list of dictionaries
# Each dictionary represents one member
Team_info = [
    {"Name": "Chioma Nnadi", "Slack_username": "Chioma", "Country": "Nigeria", "Hobby": "Writing", "Affiliation": "None", "Fav_gene": "BRCA1", "Fav_gene_ID": "672", "Fav_gene_sequence": "GCTGAGACTTCCTGGACGGGGGACAGGCTGTGGGGTTTCTCAGATAACTGGGCCCCTGCGCTCAGGAGGC","LinkedIN_ID": "https://www.linkedin.com/in/nnadichioma/", "Github_ID": "https://github.com/Nnadichioma"},

    {"Name": "Kashish Arora", "Slack_username": "Kashish", "Country": "India", "Hobby": "Reading", "Affiliation": "University of Glasgow", "Fav_gene": "CDKN1A (p21) promoter", "Fav_gene_ID": "1026", "Fav_gene_sequence": "GAACATGTCCCAACATGTTG","LinkedIN_ID": "http://www.linkedin.com/in/kashish-a-a6aa90163", "Github_ID": "https://github.com/ka080/Hackbio-stagezero/upload"},

    {"Name": "Keola Merl Joanes", "Slack_username": "Keola", "Country": "India", "Hobby": "Reading",  "Affiliation": "PCCAS", "Fav_gene": "HBB", "Fav_gene_ID": "3043", "Fav_gene_sequence": "GGGGGATATTATGAAGGGCCTTGAGCATCTGGATTCTGCCTAATAAAAAACATTTATTTTCATTGCAA","LinkedIN_ID": "www.linkedin.com/in/keola-joanes-725b6520a", "Github_ID": "https://github.com/keola04-joanes"},

    {"Name": "Lavinia Dorothea F Joseph", "Slack_username": "Lavinia", "Country": "Antigua & Barbuda", "Hobby": "Sudoku", "Affiliation": "University Mohammed V, Faculty of Medicine and Pharmacy", "Fav_gene": "DHh", "Fav_gene_ID": "50846", "Fav_gene_sequence": "GTTCCAGGTAGTGCCTGAAACTACTTTTCTGAAGAAGTATAATTAAAAGTAATCTTGTTTTGAGAA","LinkedIN_ID": "N/A", "Github_ID": "N/A"},

    {"Name": "Atairoro Joshua", "Slack_username": "Atairoro Joshua", "Country": "Nigeria", "Hobby": "Music", "Affiliation": "None", "Fav_gene": "BRCA1", "Fav_gene_ID": "672", "Fav_gene_sequence": "ATGGAAGTTGTCATTTTATAAAGTCAGTAGTTTCTTTGGCAGCAATGCCAGGAAAGGCTCTGAGGAA","LinkedIN_ID": "https://www.linkedin.com/in/atairoro-joshua-88a13424b/", "Github_ID": "https://github.com/King-AJr"},

    {"Name": "Bezaleel Akinbami", "Slack_username": "B3z", "Country": "Nigeria", "Hobby": "Gaming", "Affiliation": "None", "Fav_gene": "None", "Fav_gene_ID": "None", "Fav_gene_sequence": "None","LinkedIN_ID": "N/A", "Github_ID": "N/A"},

    {"Name": "Sharon Addy", "Slack_username": "Sharon Addy", "Country": "Ghana", "Hobby": "Repairing damaged electronics","Affiliation": "None", "Fav_gene": "MIR1-1", "Fav_gene_ID": "406904","Fav_gene_sequence": "UGGAAUGUAAAGAAGUAUGUAU","LinkedIN_ID": "https://www.linkedin.com/in/sharon-addy", "Github_ID": "https://github.com/Addymansy"}, # Added comma here

    {"Name": "Jegede Joseph.O", "Slack_username": "Joseph", "Country": "Nigeria", "Hobby": "Gaming","Affiliation": "Obafemi Awolowo University", "Fav_gene": "None", "Fav_gene_ID": "None","Fav_gene_sequence": "None","LinkedIN_ID": "N/A", "Github_ID": "N/A"}
]

# Convert the list of dictionaries into a DataFrame
df = pd.DataFrame(Team_info)

# To display final team info
print("\nHackBio_Team_Leucine_Information:\n")
print(df.to_string(index=False))

# To calculate the total number of members in the team
print(f"\nTotal_team_members: {len(df)}")
